### PR TITLE
WIP: Upgrade Django to 2.x and Celery to 4.x

### PR DESCRIPTION
**Pull request by mrs83**
- Update and squash migrations.
- Add testproject.

### CODE REVIEW

**Comment by mrs83** [comment]
@limpbrains what's the current status of the project? Is it currently maintained?

Here's what I think is missing:

- Add LICENSE file
- Update README.md
- Add extra documentation
- Add bitcoind and litecoind in regtest mode for testproject sandbox
- Add Procfile to run testproject sandbox processes
- Add .travis.yml

**Comment by limpbrains** [comment]
HI @mscam
Thanks for pull request!
You did some changes in initial migration, will it break migrations for existing projects if they will try to upgrade?

This project is maintained, I have it in production. It suits my need well.

All the Improvings that you are suggesting, are very interesting. Especially testing environment with regtest! Please, contribute, if you are interested.
Segwit would be another nice feature to have.

Regarding the license, I'm thinking about BSD, like the Django has. What do you think?

**Comment by mrs83** [comment]
Hello, thanks to you for considering my contributions. 

Let's flag this PR as WIP, as I would like to test also the upgrade of an existing installation before considering ready to be merged in a tagged branch (as I think we should keep support to LTS django releases). 

I am happy that the project is maintained and in production, and as I am new to blockchain-related programming I started to contribute to this project to learn more. 

For the license I think BSD or MIT would be fine, as it should be suitable of course for commercial use. That could be added directly on master. 

Lets' keep in touch in January, and happy new year!

**Comment by limpbrains** [comment]
I think this PR should be refactored and splited into smaller parts

* replacing CommaSeparatedIntegerField with CharField already in master, I'm gonna release new version soon
* testproject doesn't belong to this repo, it should be separate. I have old abandoned https://github.com/limpbrains/django-cc-wallet or you can create new one and link it in the Readme
* `on_delete=models.PROTECT` what is if for? Whats the use case?
* Looks like there is no need to bump django required version, or am I wrong ?

**Pull request closed without merging**
